BOARD_COLUMNS = [
    "Backlog",
    "Ready",
    "Planning",
    "Coding",
    "Testing",
    "Deploy",
    "Done",
    "Failed",
]

DEFAULT_TASKS = [
    {
        "id": "DONE-001",
        "title": "Base dashboard with GMV and net revenue cards",
        "kind": "feature",
        "status": "done",
        "summary": "Initial analytics cards for the seller cockpit.",
        "acceptance_criteria": "Dashboard shows GMV and net revenue values.",
        "target_area": "dashboard",
    },
    {
        "id": "DONE-002",
        "title": "Orders page with seeded data table",
        "kind": "feature",
        "status": "done",
        "summary": "Basic orders list with order ids, dates, statuses, and totals.",
        "acceptance_criteria": "Orders page renders a non-empty table.",
        "target_area": "orders",
    },
    {
        "id": "DONE-003",
        "title": "Products page with stock overview",
        "kind": "feature",
        "status": "done",
        "summary": "Basic product list with stock and margin percent.",
        "acceptance_criteria": "Products page shows stock and margin columns.",
        "target_area": "products",
    },
    {
        "id": "DONE-004",
        "title": "Finance page daily revenue chart",
        "kind": "feature",
        "status": "done",
        "summary": "Daily revenue history for the last week.",
        "acceptance_criteria": "Finance page renders daily revenue values.",
        "target_area": "finance",
    },
    {
        "id": "DONE-005",
        "title": "Date range filter for order analytics",
        "kind": "feature",
        "status": "done",
        "summary": "Metrics respect the selected date range.",
        "acceptance_criteria": "Dashboard totals change when date range changes.",
        "target_area": "dashboard",
    },
    {
        "id": "DONE-006",
        "title": "Baseline API health endpoint",
        "kind": "quality",
        "status": "done",
        "summary": "Health endpoint for pet app and orchestrator.",
        "acceptance_criteria": "GET /health returns ok.",
        "target_area": "platform",
    },
    {
        "id": "DONE-007",
        "title": "Dockerized pet app service",
        "kind": "quality",
        "status": "done",
        "summary": "The pet app can run inside docker compose.",
        "acceptance_criteria": "Pet app is reachable on the mapped port.",
        "target_area": "platform",
    },
    {
        "id": "DONE-008",
        "title": "Seed seller demo data",
        "kind": "quality",
        "status": "done",
        "summary": "Synthetic seller data prepared for the demo.",
        "acceptance_criteria": "Dashboard metrics are populated from seed data.",
        "target_area": "data",
    },
    {
        "id": "BL-001",
        "title": "Net revenue ignores returns for refunded orders",
        "kind": "bug",
        "status": "backlog",
        "summary": "Finance totals should subtract refunded orders.",
        "acceptance_criteria": "Net revenue excludes refunded order totals.",
        "target_area": "finance",
    },
    {
        "id": "BL-002",
        "title": "Orders sorting by date is lexicographic instead of chronological",
        "kind": "bug",
        "status": "backlog",
        "summary": "String sorting breaks the recent orders view.",
        "acceptance_criteria": "Newest orders appear first regardless of month/day formatting.",
        "target_area": "orders",
    },
    {
        "id": "BL-003",
        "title": "Dashboard totals do not react to category filter",
        "kind": "bug",
        "status": "backlog",
        "summary": "Category filter affects the table but not summary cards.",
        "acceptance_criteria": "Filtered dashboard cards match filtered dataset.",
        "target_area": "dashboard",
    },
    {
        "id": "BL-004",
        "title": "Add low stock products panel to dashboard",
        "kind": "feature",
        "status": "backlog",
        "summary": "Show products with critically low stock.",
        "acceptance_criteria": "Dashboard lists products with stock under the threshold.",
        "target_area": "dashboard",
    },
    {
        "id": "BL-005",
        "title": "Add CSV export for orders",
        "kind": "feature",
        "status": "backlog",
        "summary": "Operations needs a quick CSV export from the orders page.",
        "acceptance_criteria": "Orders page provides CSV download.",
        "target_area": "orders",
    },
    {
        "id": "BL-006",
        "title": "Highlight negative margin products",
        "kind": "feature",
        "status": "backlog",
        "summary": "Negative margin should be visible without opening product details.",
        "acceptance_criteria": "Negative margin rows are clearly highlighted.",
        "target_area": "products",
    },
    {
        "id": "BL-007",
        "title": "Return rate widget overcounts cancelled orders",
        "kind": "bug",
        "status": "backlog",
        "summary": "Cancelled orders should not increase the return rate denominator.",
        "acceptance_criteria": "Return rate excludes cancelled orders from the base.",
        "target_area": "dashboard",
    },
    {
        "id": "BL-008",
        "title": "Top products card should support brand filter",
        "kind": "feature",
        "status": "backlog",
        "summary": "Brand filter needs to propagate to top products.",
        "acceptance_criteria": "Top products card changes when a brand is selected.",
        "target_area": "products",
    },
    {
        "id": "BL-009",
        "title": "Seed more return reasons for analytics slice",
        "kind": "quality",
        "status": "backlog",
        "summary": "The demo needs a richer reasons distribution.",
        "acceptance_criteria": "Return reasons chart has at least four categories.",
        "target_area": "data",
    },
    {
        "id": "BL-010",
        "title": "Add build badge with deployed task id",
        "kind": "feature",
        "status": "backlog",
        "summary": "The live app should reveal which task version is deployed.",
        "acceptance_criteria": "UI shows a build badge with task id and timestamp.",
        "target_area": "platform",
    },
    {
        "id": "BL-011",
        "title": "Improve empty state for no matching orders",
        "kind": "feature",
        "status": "backlog",
        "summary": "Current empty table is unclear.",
        "acceptance_criteria": "Users see a readable empty state with next actions.",
        "target_area": "orders",
    },
    {
        "id": "BL-012",
        "title": "Add smoke test for dashboard home page",
        "kind": "quality",
        "status": "backlog",
        "summary": "The demo needs one more smoke test for confidence.",
        "acceptance_criteria": "Test suite covers the dashboard landing page.",
        "target_area": "platform",
    },
]
